# name: CI/CD Pipeline for CSCI5300 Project
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get Latest Code from Repo
#         uses: actions/checkout@v2
#       - name: Say Hello to the World
#         run: echo "Hello, World!"

name: CSCI5300 Build Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Latest Code from Repo
      uses: actions/checkout@v2
    - name: Setup Node.Js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Dependencies
      run: |
        npm install
        npm install --prefix client
    - name: Install devDependencies
      run: npm install --save-dev @babel/plugin-proposal-private-property-in-object
    - name: Build Frontend
      run: |
        npm run build --prefix client
    - name: Deploy
      run: |
        echo "Deploy steps go here"
        echo "Hello, After successful Build!"
